// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qsmzukdvivwzdvryxmct.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFzbXp1a2R2aXZ3emR2cnl4bWN0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNTEzNDAsImV4cCI6MjA1ODgyNzM0MH0.nACA_65BTwVqjtWKwUV2uGOO1lX-Rp4RFxiTLZTySNc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);